# Generated by Django 4.0.5 on 2022-06-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_dos_alter_alumnos_options_alter_alumnos_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dos',
        ),
    ]
