# Generated by Django 4.0.5 on 2022-06-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_delete_dos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
