# Generated by Django 4.0.5 on 2022-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
