# Generated by Django 4.0.5 on 2022-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_alter_archivos_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
