# Generated by Django 4.0.5 on 2022-06-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcurso', models.SmallIntegerField(verbose_name='Clave Curso')),
                ('nombre', models.TextField(max_length=30, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción del Curso')),
                ('activo', models.BooleanField(verbose_name='Estatus del Curso')),
                ('duracion', models.SmallIntegerField(verbose_name='Duración del Curso')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['-created'],
            },
        ),
    ]
