# Generated by Django 4.0.5 on 2022-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='duracion',
            field=models.PositiveSmallIntegerField(verbose_name='Duración del Curso'),
        ),
    ]
