# Generated by Django 4.0.5 on 2022-06-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='id',
        ),
        migrations.AlterField(
            model_name='cursos',
            name='idcurso',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Clave Curso'),
        ),
    ]
